version: "3.9"

services:
  web:
    container_name: payment-api-sevice_web
    build: .
    command: []
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached # optimize for macOS; remove for production
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: payment-api-sevice_db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
